[package]
name = "snowflake-connector-rs"
version = "0.6.5"
edition = "2024"
authors = ["kenkoooo <kenkou.n@gmail.com>"]
description = "A Rust client for Snowflake"
readme = "README.md"
repository = "https://github.com/estie-inc/snowflake-connector-rs"
license = "MIT"
keywords = ["snowflake", "database", "sql", "client"]

[dependencies]
http = "1.1"
reqwest = { version = "0.12", features = [
    "json",
    "gzip",
    "rustls-tls",
], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
uuid = { version = "1.11", features = ["v4"] }
flate2 = "1.0"
tokio = { version = "1.41", features = ["rt"] }
chrono = "0.4"
pkcs8 = { version = "0.10", features = ["pem", "pkcs5", "encryption"] }
rsa = "0.9"
sha2 = "0.10"
base64 = "0.22"
jsonwebtoken = "9.1"

[dev-dependencies]
tokio = { version = "1.41", features = ["macros", "rt-multi-thread"] }
